version: '3'

services:
  reverse-proxy:
    image: traefik:v2.1
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./data:/opt/data
    labels:
      traefik.http.routers.http_catchall.rule: HostRegexp(`{any:.+}`)
      traefik.http.routers.http_catchall.entrypoints: http
      traefik.http.routers.http_catchall.middlewares: https_redirect
      traefik.http.middlewares.https_redirect.redirectscheme.scheme: https
      traefik.http.middlewares.https_redirect.redirectscheme.permanent: true
      traefik.http.middlewares.headersMiddleware.headers.sslProxyHeaders: true
networks:
  proxy:
    external: true
